name: Update Finance Data

on:
  workflow_dispatch:
  schedule:
    - cron: '30 9,23 * * 1-5'

# 저장소 쓰기 권한 추가
permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install finance-datareader pandas requests python-dotenv beautifulsoup4
      
      - name: Debug directory structure
        run: |
          echo "Current directory: $(pwd)"
          ls -la
      
      - name: Run original data collection script
        run: python finance_data_collector.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      
      - name: Run exchange rate update script
        run: python exchange_rate_updater.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

      - name: Generate timestamp
        run: echo "Last run $(date)" > last_run.log
      
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add last_run.log
          git commit -m "Update finance data and last run timestamp" || echo "No changes"
          git push
